### ISSUE TITLE
Python 3 への移行

### ISSUE THREAD

**Issue by hoshizuki** [vippool/clerk#9]
開発時、GAE が Python 2.7 しか対応していなかったため、
Python 2.7 で実装されているが、Python 2.7 のサポートが
もうすぐ切れる＆GAE が Python 3 に対応したので、
移行作業を行う必要がある。

**Comment by hoshizuki** [comment]
作業依頼詳細

１．PC の開発環境構築
以下のものをインストールする必要があります。
・Google Cloud SDK
　・インストール時に Bundled Python は外してください（Python 2.7 がインストールされるため）
・Python 3
・MySQL (Connector もインストールする)

２．MySQLdb のインストール
・python -m pip install MySQL-python で行けるかも？
　・もしかすると、Visual Studio のバージョンの関係でエラーが出るので、以下の対応が必要かも。

２．１．シンボリックリンク作成
C:\Program Files\MySQL\MySQL Connector C 6.1\include>mklink config-win.h my_config.h
パスは実際のものに合わせる必要があるかも。

２．２．MySQLdb のインストール
MSVS x64 開発者コマンドプロンプトにて。
set VS90COMNTOOLS=%VS140COMNTOOLS%
set INCLUDE=%INCLUDE%C:\Program Files\MySQL\MySQL Connector C 6.1\include
set LIB=%LIB%C:\Program Files\MySQL\MySQL Connector C 6.1\lib\vs14
python -m pip install MySQL-python
右辺は実際のものに合わせる必要があるかも。

３．app.yaml の更新
https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/config-files
を参考に修正。

４．main.py / base_handler.py の修正
webapp2 から flask に移行する。
全てのリクエストは BaseHandler の派生クラスとして実装されているので、
何かしら包括的に受け取るハンドラを作った方がコードはきれいかもしれない。

５．config.py の修正
環境に合わせて。MySQL のユーザも作成しておく。

６．dev_appserver.py app.yaml でサーバ起動
たぶん動かないのでいろいろ直す。

７．まずは update_db API の動作確認
何度かアクセスして、期待通りの内容が MySQL に書かれていることを確認する。

８．その他の API の動作確認

**Comment by hoshizuki** [comment]
動作しない状態で master にマージしたくないため、
master から一旦 develop ブランチを派生して、そこから python3 ブランチを派生して作業してください。
３＆４で一度プルリクをレビューします。５はうっかりコミットしないように気を付けてください。

**Comment by ry0y4n** [comment]
# 「２．MySQLdb のインストール」でのエラー
## 作業環境
- Windows10 (64bit)
- Python 3.8.5
- MySQL 8.0.21 for Win64 on x86_64 (MySQL Community Server - GPL)
- Visual Studio 2019
## エラー内容
`python -m pip install MySQL-python` にてインストールを試みるものの、エラーが出力されてしまいます。

`_mysql.c(42): fatal error C1083: include ファイルを開けません。'config-win.h':No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2`

## 試したこと
**2-1.** と **2-2.** に記載されていたトラブルシューティング。
右辺を実際のものに対応させて行いました。その際、変更となった点は
```
set VS90COMNTOOLS=%VS140COMNTOOLS%
```
です。https://qiita.com/softgate/items/b9e04da8f8fc9f180855 の記事によるとVS2019では`VS160COMNTOOLS`のようでしたので右辺を変更しました。
しかしエラーは変わらず出力されています。

**Comment by ry0y4n** [comment]
# 続き
**2-2.** の一部コマンドを修正したものを実行すると、config-win.hが見つからない趣旨のエラーがなくなりました。
```
set INCLUDE=%INCLUDE%;C:\Program Files\MySQL\MySQL Connector C 6.1\include
set LIB=%LIB%;C:\Program Files\MySQL\MySQL Connector C 6.1\lib\vs14
```

代わりに新しいエラーが出力されました。

`_mysql.c
    _mysql.c(297): warning C4090: '=': 異なる 'const' 修飾子です。
    _mysql.c(327): warning C4090: '=': 異なる 'const' 修飾子です。
    _mysql.c(623): warning C4090: '=': 異なる 'const' 修飾子です。
    _mysql.c(624): warning C4090: '=': 異なる 'const' 修飾子です。
    _mysql.c(625): warning C4090: '=': 異なる 'const' 修飾子です。
    _mysql.c(626): warning C4090: '=': 異なる 'const' 修飾子です。
    _mysql.c(627): warning C4090: '=': 異なる 'const' 修飾子です。
    _mysql.c(1118): warning C4090: '=': 異なる 'const' 修飾子です。
    _mysql.c(1161): warning C4090: '=': 異なる 'const' 修飾子です。
    _mysql.c(1165): warning C4090: '=': 異なる 'const' 修飾子です。
    _mysql.c(1162): warning C4996: 'PyUnicode_GetSize': deprecated in 3.3
    _mysql.c(1532): warning C4018: '<': signed と unsigned の数値を比較しようとしました。`

`python38.lib(python38.dll) : fatal error LNK1112: モジュールのコンピューターの種類 'x64' は対象コンピューターの種類 'x86' と競合しています。
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x86\\link.exe' failed with exit status 1112`

**Comment by ry0y4n** [comment]
# 続き (Fin.)
x64の開発者コマンドプロンプトを使用することで、無事インストール完了。

**Comment by hoshizuki** [comment]
7 まで完了しているようなので、
8 以降の作業をもう少し詳細に解説します。

まず、送金系 API 以外の動作確認は済んでいるとのことなので、
・テストネットをローカルの MySQL に同期する
・適当な秘密鍵で送金テストを行う
・explorer.vippool.net でテストネットを確認して正常に送金できていることを確認する
で OK です。

なお、送金の手順として、
・preparetx でトランザクションを仮組みして署名対象ハッシュの作成
・submittx で一旦受け付けて TaskQueue に積む
・TaskQueue から呼ばれる sendrawtransaction で実際にコインデーモンに投げる
という手順を踏んでいるため、TaskQueue を Cloud Task 等へ置き換える作業が必要になります。

TaskQueue は、
・cron から update_db (GET) を呼ぶ
・TaskQueue に update_db (POST) を積む
・update_db (POST) で実際に DB 更新を行う
でも使用しているため、２か所の変更となりますが、
GAE 非依存というのも魅力的なので、可能であれば Cloud Task 以外への移行も検討してもらえると助かります。

**Comment by ry0y4n** [comment]
「適当な秘密鍵」の入手としてどのような方法があるのでしょうか？
送金テストをするにあたって、「すでにテストネットに記帳されている残高をもつアカウント」が必要と認識しているのですが、僕が思ったのは自前アカウントでテストネットマイニングして、テスト用アカウント（適当な秘密鍵）とするということでしょうか？

**Comment by hoshizuki** [comment]
秘密鍵は、256bit 乱数で作成してください。送信元・送信先があるので２つ必要です。
openssl rand 32 -hex
あたりがお手軽です。テストネットの残高は私がいくらか持っていますので、
作成した秘密鍵に対応する公開鍵またはコインアドレスを教えていただければ送金します。
この辺りの処理はもう１つの OSS、VIPPOOL storage の方を実行してみたり読んでいただければと思います。

**Comment by hoshizuki** [comment]
完了。
